# basic info
title: Juncheng Liu @ NUS
name: Juncheng Liu
logo: /assets/img/my_pic.jpg
description: PhD Candidate at NUS
location: xxxx
email: juncheng.liu@u.nus.edu
github: liu-jc
linkedin: juncheng-liu
# Others 
show_downloads: false 
google_analytics:
theme: jekyll-theme-minimal
